### ISSUE TITLE
Stuck on Create_Collectible.py deployment

### ISSUE THREAD

**Issue by SiKi02** [PatrickAlphaC/nft-mix#102]
Error: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

Helpful_scripts.py
```
from` brownie import AdvancedCollectible, accounts, config, interface, network 

def get_breed(breed_number):
    switch = {0: 'PUG?', 1: 'SHIBA_INU', 2: 'ST_BERNARD'}
    return switch[breed_number]

def fund_advanced_collectible(nft_contract):
    dev = accounts.add(config['wallets']['from_key'])
    link_token = interface.LinkTokenInterface(config['networks'][network.show_active()]['link_token'])
    link_token.transfer(nft_contract, 1000000000000000000, {'from':dev})
```

AdvancedCollectible.sol
```
// SPDX-License-Identifier: MIT
pragma solidity 0.6.6;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@chainlink/contracts/src/v0.6/VRFConsumerBase.sol";

contract AdvancedCollectible is ERC721, VRFConsumerBase {

    bytes32 internal keyHash;
    uint256 public fee;
    uint256 tokenCounter;

    enum Breed{PUG, SHIBA_INU, ST_BERNARD}

    mapping(bytes32 => address) public requestIDToSender;
    mapping(bytes32 => string) public requestIDToTokenURI; 
    mapping(uint256 => Breed) public tokenIDToBreed;
    mapping(bytes32 => uint256) public requestIDToTokenID;

    event RequestedCollectible(bytes32 indexed requestID);
    
    constructor(address _VRFCoordinator, address _LinkToken, bytes32 _keyhash) public
    VRFConsumerBase(_VRFCoordinator, _LinkToken)
    ERC721("Doggies", "DOG")
    {
        keyHash = _keyhash;
        fee= 0.1 * 10 ** 18; //0.1 LINK
        tokenCounter = 0;
    }

    function createCollectible(string memory tokenURI) public returns (bytes32) {
        bytes32 requestID = requestRandomness(keyHash, fee);
        requestIDToSender[requestID] = msg.sender;
        requestIDToTokenURI[requestID] = tokenURI;
        emit RequestedCollectible(requestID);
    }

    function fulfillRandomness(bytes32 requestID, uint256 randomNumber) internal override {
        address dogOwner = requestIDToSender[requestID];
        string memory tokenURI = requestIDToTokenURI[requestID];
        uint256 newItemID = tokenCounter;
        _safeMint(dogOwner, newItemID);
        _setTokenURI(newItemID, tokenURI);
        Breed breed = Breed(randomNumber % 3);
        tokenIDToBreed[newItemID] = breed;
        requestIDToTokenID[requestID] = newItemID;
        tokenCounter = tokenCounter + 1;
        }

    function setTokenURI(uint256 tokenID, string memory _tokenURI) public {
        require(
            _isApprovedOrOwner(_msgSender(), tokenID),
            "ERC721: transfer caller is not owner nor approved"
        );
        _setTokenURI(tokenID, _tokenURI);
    }
}
```

Create_collectible.py
```
from brownie import AdvancedCollectible, accounts, config
from scripts.helpful_scripts import get_breed
import time

def main():
    dev = accounts.add(config['wallets']['from_key'])
    advanced_collectible = AdvancedCollectible[len(AdvancedCollectible) - 1]
    transaction = advanced_collectible.createCollectible("None", {'from': dev},)
    transaction.wait(1)
    time.sleep(35)
    requestId = transaction.events['RequestedCollectible']['requestID']
    token_id = advanced_collectible.requestIDToTokenID(requestId)
    breed = get_breed(advanced_collectible.tokenIDToBreed(token_id))
    print('Dog breed of token ID {} is {}'.format(token_id, breed))
```

Brownie-config.yaml
```
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
networks:
  default: development
  rinkeby:
    vrf_coordinator: "0x6168499c0cFfCaCD319c818142124B7A15E857ab"
    link_token: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    keyhash: "0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc"
    fee: 100000000000000000

```
Complete error tab:
```
brownie run scripts/advanced_collectible/create_collectible.py --network rinkeby
Brownie v1.18.2 - Python development framework for Ethereum

ScratchProject is the active project.

Running 'scripts/advanced_collectible/create_collectible.py::main'...
  File "brownie/_cli/run.py", line 51, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 110, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/advanced_collectible/create_collectible.py", line 8, in main
    transaction = advanced_collectible.createCollectible("None", {'from': dev},)
  File "brownie/network/contract.py", line 1861, in __call__
    return self.transact(*args)
  File "brownie/network/contract.py", line 1734, in transact
    return tx["from"].transfer(
  File "brownie/network/account.py", line 644, in transfer
    receipt, exc = self._make_transaction(
  File "brownie/network/account.py", line 727, in _make_transaction
    raise VirtualMachineError(e) from None
  File "brownie/exceptions.py", line 93, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'execution reverted'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.

```

Thanks people!
