### ISSUE TITLE
Deploy on mainnet

### ISSUE THREAD

**Issue by DevCode01** [PatrickAlphaC/nft-mix#31]
Hello everybody.
I just would like to know how to deploy the simple contract on OpenSea main net ?
All is working on testnet.
Thank you

**Comment by PatrickAlphaC** [comment]
You need to add networking information for mainnet in your `brownie-config.yaml`

For example:

```
  kovan:
    vrf_coordinator: '0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9'
    link_token: '0xa36085F69e2889c224210F603D836748e7dC0088'
    keyhash: '0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4'
    fee: 100000000000000000
    oracle: '0x2f90A6D021db21e1B2A077c5a37B3C7E75D15b7e'
    jobId: '29fa9aa13bf1468788b7cc4a500a45b8'
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'
```

This is the setup for kovan, you'd have to add a `mainnet` key, and all the key value pairs.

Then, so long as you have a `WEB3_INFURA_PROJECT_ID` environment variable, you can just do `brownie run scripts/<whatever-script> --network mainnet`
